config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :users
  resources :companies
  resources :customers
  resources :items
  resources :estimates
  resources :estimate_details
  resources :estimate_pdf, only: [:index, :show]

  get "signup", to: "signup#index"
  resources :signup do
    collection do
      get 'step1'
      post 'step2'  #入力が全て完了
      get 'complete'  #登録完了後
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  VALID_PHONE_REGEX = /\A0(\d{1}[-(]?\d{4}|\d{2}[-(]?\d{3}|\d{3}[-(]?\d{2}|\d{4}[-(]?\d{1})[-)]?\d{4}\z|\A0[5789]0[-]?\d{4}[-]?\d{4}\z/
  VALID_POSTNUM_REGEX = /\A\d{3}[-]\d{4}\z/
  belongs_to :user
  validates :name, presence: true
  validates :tel, presence: true, format: { with: VALID_PHONE_REGEX }
  validates :fax, presence: true, format: { with: VALID_PHONE_REGEX }
  validates :postal_code, presence: true, format: { with: VALID_POSTNUM_REGEX }
  validates :address, presence: true
end 

app/models/contact_person.rb
class ContactPerson < ApplicationRecord
  has_one :estimate, dependent: :destroy
  belongs_to :customer
  validates :name, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :contact_persons, dependent: :destroy
  has_many :estimates, dependent: :destroy
  belongs_to :user
  validates :company_name, presence: true
end

app/models/estimate.rb
class Estimate < ApplicationRecord
  has_many :estimate_details, dependent: :destroy
  belongs_to :user
  belongs_to :customer
  belongs_to :contact_person
  validate :date_before_start

  def date_before_start
    return if effective.blank?
    errors.add(:effective, "は今日以降のものを選択してください") if effective < Date.today
  end

end

app/models/estimate_detail.rb
class EstimateDetail < ApplicationRecord
  belongs_to :estimate
  belongs_to :item
  validates :volume, :price, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many :estimate_details, dependent: :destroy
  validates :item_name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one :company, dependent: :destroy
  has_many :customers, dependent: :destroy
  has_many :items, dependent: :destroy
  has_many :estimates, dependent: :destroy
  accepts_nested_attributes_for :company, allow_destroy: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, uniqueness:true, length:{ maximum: 255 },
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, length: { minimum: 6 },
            format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i }
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  before_action :authenticate_user!
  before_action :set_company

  def edit
  end

  def update
    binding.pry
    if @company.update(company_params)
      redirect_to user_path(@user)
    else
      redirect_to edit_company_path
    end
  end

  private

  def set_company
    @user = current_user
    @company = @user.company
  end

  def company_params
    params.require(:company).permit(:name, :tel, :fax, :postal_code, :address).merge(user_id: current_user.id)
  end
end

app/controllers/estimates_controller.rb
class EstimatesController < ApplicationController
  before_action :authenticate_user!
  def index
    @user = current_user
    @company = 
    @customers = @user.customers
    @estimates = @user.estimates.order("created_at DESC")
    
  end
  def show
    @estimate = Estimate.find(params[:id])
    @customer = @estimate.customer
    @contact_person = @estimate.contact_person
    @user = current_user
  end
  def new
    @estimate = EstimateForm.new
    @user = current_user
  end
  def create
    @estimate = EstimateForm.new(estimate_params)
    if @estimate.save
      redirect_to estimates_path, notice: '見積もり内容を登録しました。'
    else
      render :new, status: :unprocessable_entity
    end
  end
  def edit
    # @estimate = EstimateForm.find()
    # @user = current_user
  end
  def update
    # @estimate = EstimateForm.new(estimate_params, @estimate)
  end
  private
  def estimate_params
    params.require(:estimate_form).permit(
  :company_name, :department, :position, :name, :effective, :note, items: [:item_name, :volume, :price]
      ).merge(user_id: current_user.id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @user = current_user
  end

  def show
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :authenticate_user!

  def index
    @user = current_user
    @items = @user.items
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to items_path, notice: '商品を登録しました。'
    else
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to items_path
    else
      render :edit
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_path, alert: '商品を削除しました'
  end

  private

  def item_params
    params.require(:item).permit(
      :item_name
    ).merge(user_id: current_user.id)
  end
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController

  before_action :save_step1_to_session, only: :step2
  before_action :save_step2_to_session, only: :step3

  def step1
    @user = User.new
    @user.build_company
  end

  def save_step1_to_session
    session[:user_params] = user_params
    @user = User.new(session[:user_params])
    render '/signup/step1' unless @user.valid?
  end 

  def step2
    session[:user_params] = user_params
    @user = User.new
    @user.build_company
  end

  def create
    @user = User.new(session[:user_params])
    @user.build_company(user_params[:company_attributes])
    if @user.save
      session[:id] = @user.id
      sign_in @user
      redirect_to root_path
    else
      @user.build_company(user_params[:company_attributes])
      render '/signup/step2'
    end
  end

  private
  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :password, 
      :password_confirmation, 
      company_attributes: [:id, :name, :tel, :fax, :postal_code, :address]
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def index
  end
  
  def show
    @user = User.find(params[:id])
    @company = @user.company
    @estimates = @user.estimates.order("created_at DESC")
  end

  def edit
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/estimate_details_helper.rb
module EstimateDetailsHelper
end

app/helpers/estimates_helper.rb
module EstimatesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/estimates/edit.html.haml
= form_with model: @estimate, url: "/estimates", local: true do |f|
  .input-area
    = f.label :company_name, "会社名", class: "input-area__title"
    = f.text_field :company_name, autofocus: true, autocomplete: "company_name", class: "input-area__text-field"
  .input-area
    = f.label :department, "部署", class: "input-area__title"
    = f.text_field :department, autofocus: true, autocomplete: "department", class: "input-area__text-field"
  .input-area
    = f.label :position, "役職", class: "input-area__title"
    = f.text_field :position, autofocus: true, autocomplete: "position", class: "input-area__text-field"
  .input-area
    = f.label :name, "担当者名", class: "input-area__title"
    = f.text_field :name, autofocus: true, autocomplete: "name", class: "input-area__text-field"
  .input-area
    = f.label :effective, "有効期限", class: "input-area__title"
    = f.text_field :effective, autofocus: true, autocomplete: "effective", class: "input-area__text-field"
  .input-area
    = f.label :item_name, "商品名", class: "input-area__title"
    = f.text_field :item_name, autofocus: true, autocomplete: "item_name", class: "input-area__text-field"
  .input-area
    = f.label :volume, "数量", class: "input-area__title"
    = f.text_field :volume, autofocus: true, autocomplete: "volume", class: "input-area__text-field"
  .input-area
    = f.label :price, "価格", class: "input-area__title"
    = f.text_field :price, autofocus: true, autocomplete: "price", class: "input-area__text-field"
  .input-area
    = f.label :note, "備考", class: "input-area__title"
    = f.text_field :note, autofocus: true, autocomplete: "note", class: "input-area__text-field"
  .input-area
    = f.submit "登録", class: "submit-btn"

app/views/estimates/index.html.haml
.main
  .estimates
    %h1.estimates__title
      = @user.name
      様の見積履歴
    .estimates__content
      .estimate
        .estimate__header
          %h3 見積一覧
        .estimate__body
          .informationbox
            - @estimates.each do |estimate|
              .informationbox__inner
                = l estimate.created_at, format: :short
                .estimate-content
                  .customer-info
                    .customer-info__company
                      #{estimate.customer.company_name} 御中
                    .customer-info__department
                      = estimate.contact_person.department
                    .customer-info__position
                      = estimate.contact_person.position
                    .customer-info__name
                      #{estimate.contact_person.name} 様
                  .details
                    - estimate.estimate_details.each.with_index do |detail, index|
                      .details__info
                        .details__info__item-name
                          #{index + 1}, #{detail.item.item_name}
                        .details__info__volume
                          #{detail.volume} 個
                        .details__info__price
                          #{detail.price} 円
                .pdf-link
                  = link_to "見積書発行", estimate_pdf_path(estimate, format: "pdf"), class: "pdf-btn"

app/views/estimates/new.html.haml
.main
  .form-estimate
    .form-estimate__title
      見積書作成ページ
    = form_with model: @estimate, url: "/estimates", local: true do |f|
      .form-estimate__content
        .form-estimate__content__right
          .form-estimate__content__right__input
            .input-area
              = f.label :company_name, "会社名", class: "input-area__title"
              = f.text_field :company_name, autofocus: true, autocomplete: "company_name", class: "input-area__text-field"
            .input-area
              = f.label :department, "部署", class: "input-area__title"
              = f.text_field :department, autofocus: true, autocomplete: "department", class: "input-area__text-field"
            .input-area
              = f.label :position, "役職", class: "input-area__title"
              = f.text_field :position, autofocus: true, autocomplete: "position", class: "input-area__text-field"
            .input-area
              = f.label :name, "担当者名", class: "input-area__title"
              = f.text_field :name, autofocus: true, autocomplete: "name", class: "input-area__text-field"
            .input-area
              = f.label :effective, "有効期限", class: "input-area__title"
              = f.date_field :effective, autofocus: true, autocomplete: "effective", class: "input-area__text-field"
        .form-estimate__content__left
          .form-estimate__content__left__input
            .form-estimate__content__left__input__add{"data-formno" => "0"}
              .input-area-left.item-name
                = f.label :item_name, "商品名", class: "input-area-left__title"
                = f.text_field :item_name, autofocus: true, autocomplete: "item_name", class: "input-area-left__text-field input-item-name", name: "estimate_form[items][0][item_name]"
              .input-area-left.item-volume
                = f.label :volume, "数量", class: "input-area-left__title"
                = f.text_field :volume, autofocus: true, autocomplete: "volume", class: "input-area-left__text-field-right", name: "estimate_form[items][0]volume]"
              .input-area-left.item-price
                = f.label :price, "価格", class: "input-area-left__title"
                = f.text_field :price, autofocus: true, autocomplete: "price", class: "input-area-left__text-field", name: "estimate_form[items][0]price]"
              %button.item-add-js-btn(type="button")
                +
              %button.item-delete-js-btn(type="button")
                &minus;
          .form-estimate__content__left__input
            .input-area
              = f.label :note, "備考", class: "input-area-left__title"
              = f.text_area :note, autofocus: true, autocomplete: "note", class: "input-area-left__remarks"
      .form-estimate__btn
        .input-area
          = f.submit "登録", class: "submit-btn"

app/views/estimates/show.html.haml
= @customer.company_name
= @contact_person.name
= link_to "〇〇会社見積書PDF", estimate_pdf_path(@estimate, format: "pdf")