config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :users
  resources :companies
  resources :customers
  resources :items
  resources :estimates
  resources :estimate_details
  resources :estimate_pdf, only: [:index, :show]

  get "signup", to: "signup#index"
  resources :signup do
    collection do
      get 'step1'
      post 'step2'  #入力が全て完了
      get 'complete'  #登録完了後
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  VALID_PHONE_REGEX = /\A0(\d{1}[-(]?\d{4}|\d{2}[-(]?\d{3}|\d{3}[-(]?\d{2}|\d{4}[-(]?\d{1})[-)]?\d{4}\z|\A0[5789]0[-]?\d{4}[-]?\d{4}\z/
  VALID_POSTNUM_REGEX = /\A\d{3}[-]\d{4}\z/
  belongs_to :user
  validates :name, presence: true
  validates :tel, presence: true, format: { with: VALID_PHONE_REGEX }
  validates :fax, presence: true, format: { with: VALID_PHONE_REGEX }
  validates :postal_code, presence: true, format: { with: VALID_POSTNUM_REGEX }
  validates :address, presence: true
end 

app/models/contact_person.rb
class ContactPerson < ApplicationRecord
  has_one :estimate, dependent: :destroy
  belongs_to :customer
  validates :name, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :contact_persons, dependent: :destroy
  has_many :estimates, dependent: :destroy
  belongs_to :user
  validates :company_name, presence: true
end

app/models/estimate.rb
class Estimate < ApplicationRecord
  has_many :estimate_details, dependent: :destroy
  belongs_to :user
  belongs_to :customer
  belongs_to :contact_person
  validate :date_before_start

  def date_before_start
    return if effective.blank?
    errors.add(:effective, "は今日以降のものを選択してください") if effective < Date.today
  end

end

app/models/estimate_detail.rb
class EstimateDetail < ApplicationRecord
  belongs_to :estimate
  belongs_to :item
  validates :volume, :price, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many :estimate_details, dependent: :destroy
  validates :item_name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one :company, dependent: :destroy
  has_many :customers, dependent: :destroy
  has_many :items, dependent: :destroy
  has_many :estimates, dependent: :destroy
  accepts_nested_attributes_for :company, allow_destroy: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, uniqueness:true, length:{ maximum: 255 },
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, length: { minimum: 6 },
            format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i }
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  before_action :authenticate_user!
  before_action :set_company

  def edit
  end

  def update
    binding.pry
    if @company.update(company_params)
      redirect_to user_path(@user)
    else
      redirect_to edit_company_path
    end
  end

  private

  def set_company
    @user = current_user
    @company = @user.company
  end

  def company_params
    params.require(:company).permit(:name, :tel, :fax, :postal_code, :address).merge(user_id: current_user.id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @user = current_user
  end

  def show
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :authenticate_user!

  def index
    @user = current_user
    @items = @user.items
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to items_path, notice: '商品を登録しました。'
    else
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to items_path
    else
      render :edit
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_path, alert: '商品を削除しました'
  end

  private

  def item_params
    params.require(:item).permit(
      :item_name
    ).merge(user_id: current_user.id)
  end
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController

  before_action :save_step1_to_session, only: :step2
  before_action :save_step2_to_session, only: :step3

  def step1
    @user = User.new
    @user.build_company
  end

  def save_step1_to_session
    session[:user_params] = user_params
    @user = User.new(session[:user_params])
    render '/signup/step1' unless @user.valid?
  end 

  def step2
    session[:user_params] = user_params
    @user = User.new
    @user.build_company
  end

  def create
    @user = User.new(session[:user_params])
    @user.build_company(user_params[:company_attributes])
    if @user.save
      session[:id] = @user.id
      sign_in @user
      redirect_to root_path
    else
      @user.build_company(user_params[:company_attributes])
      render '/signup/step2'
    end
  end

  private
  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :password, 
      :password_confirmation, 
      company_attributes: [:id, :name, :tel, :fax, :postal_code, :address]
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def index
  end
  
  def show
    @user = User.find(params[:id])
    @company = @user.company
    @estimates = @user.estimates.order("created_at DESC")
  end

  def edit
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/estimate_details_helper.rb
module EstimateDetailsHelper
end

app/helpers/estimates_helper.rb
module EstimatesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.haml
%main.home
  .home__inner
    .home__inner__message
      .home__inner__message__top
        %h1.home__inner__message__text
          見積書を
          %br>/
          かんたん作成！まとめて管理！Yeah!
    - if user_signed_in?
      .create_documents
        .create_documents__btn
          = link_to "見積書を作成する", new_estimate_path, class: "create_documents__btn__text"
    - else
      .devise_box
        .devise_box__btn
          = link_to "ログイン", new_user_session_path, class: "devise_box__btn__text"
        .devise_box__btn
          = link_to "新規登録", step1_signup_index_path, class: "devise_box__btn__text"

app/views/signup/step1.html.haml
%main.signup
  %h1.signup__title
    Premiに登録する
  .signup__form
    .signup__form__input
      = form_for @user, url: step2_signup_index_path do |f|
        = render 'layouts/error_messages', model: f.object
        = hidden_field_tag :current_step, 'step1'
        .input-area
          = f.label :name, "名前", class: "input-area__title"
          %span.input-area__required 必須
          %br/
          = f.text_field :name, autofocus: true, autocomplete: "name", class: "input-area__text-field"
        .input-area
          = f.label :email, "メールアドレス", class: "input-area__title"
          %span.input-area__required 必須
          %br/
          = f.text_field :email, autofocus: true, autocomplete: "email", class: "input-area__text-field"
        .input-area
          = f.label :password, "パスワード", class: "input-area__title"
          %span.input-area__required 必須
          %br/
          - if @minimum_password_length
            %em
              (#{@minimum_password_length} 文字以上の半角英数記号)
          %br/
          = f.password_field :password, autocomplete: "new-password", class: "input-area__text-field"
        .input-area
          = f.label :password_confirmation, "パスワード確認", class: "input-area__title"
          %span.input-area__required 必須
          %br/
          = f.password_field :password_confirmation, autocomplete: "new-password", class: "input-area__text-field"
        .input-area
          = f.submit "会社情報入力", class: "submit-btn"

app/views/signup/step2.html.haml
%main.signup
  %h1.signup__title
    会社情報入力
  .signup__form
    .signup__form__input
      = form_for @user, url: signup_index_path, method: :post do |f|
        = render 'layouts/error_messages', model: f.object
        = hidden_field_tag :current_step, 'step2'
        = f.fields_for :company do |f|
          .input-area
            = f.label :name, "会社名", class: "input-area__title"
            %span.input-area__required 必須
            %br/
            = f.text_field :name, autofocus: true, autocomplete: "name", class: "input-area__text-field"
          .input-area
            = f.label :tel, "電話番号", class: "input-area__title"
            %span.input-area__required 必須
            %br/
            = f.text_field :tel, autofocus: true, autocomplete: "tel", class: "input-area__text-field"
          .input-area
            = f.label :fax, "FAX番号", class: "input-area__title"
            %span.input-area__required 必須
            %br/
            = f.text_field :fax, autofocus: true, autocomplete: "fax", class: "input-area__text-field"
          .input-area
            = f.label :postal_code, "郵便番号", class: "input-area__title"
            %span.input-area__required 必須
            %br/
            = f.text_field :postal_code, autofocus: true, autocomplete: "postal_code", class: "input-area__text-field"
          .input-area
            = f.label :address, "住所", class: "input-area__title"
            %span.input-area__required 必須
            %br/
            = f.text_field :address, autofocus: true, autocomplete: "address", class: "input-area__text-field"
          .input-area
            = f.submit "登録を完了する", class: "submit-btn"