config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :users
  resources :companies
  resources :customers
  resources :items
  resources :estimates
  resources :estimate_details
  resources :estimate_pdf, only: [:index, :show]

  get "signup", to: "signup#index"
  resources :signup do
    collection do
      get 'step1'
      post 'step2'  #入力が全て完了
      get 'complete'  #登録完了後
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  VALID_PHONE_REGEX = /\A0(\d{1}[-(]?\d{4}|\d{2}[-(]?\d{3}|\d{3}[-(]?\d{2}|\d{4}[-(]?\d{1})[-)]?\d{4}\z|\A0[5789]0[-]?\d{4}[-]?\d{4}\z/
  VALID_POSTNUM_REGEX = /\A\d{3}[-]\d{4}\z/
  belongs_to :user
  validates :name, presence: true
  validates :tel, presence: true, format: { with: VALID_PHONE_REGEX }
  validates :fax, presence: true, format: { with: VALID_PHONE_REGEX }
  validates :postal_code, presence: true, format: { with: VALID_POSTNUM_REGEX }
  validates :address, presence: true
end 

app/models/contact_person.rb
class ContactPerson < ApplicationRecord
  has_one :estimate, dependent: :destroy
  belongs_to :customer
  validates :name, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :contact_persons, dependent: :destroy
  has_many :estimates, dependent: :destroy
  belongs_to :user
  validates :company_name, presence: true
end

app/models/estimate.rb
class Estimate < ApplicationRecord
  has_many :estimate_details, dependent: :destroy
  belongs_to :user
  belongs_to :customer
  belongs_to :contact_person
  validate :date_before_start

  def date_before_start
    return if effective.blank?
    errors.add(:effective, "は今日以降のものを選択してください") if effective < Date.today
  end

end

app/models/estimate_detail.rb
class EstimateDetail < ApplicationRecord
  belongs_to :estimate
  belongs_to :item
  validates :volume, :price, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many :estimate_details, dependent: :destroy
  validates :item_name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one :company, dependent: :destroy
  has_many :customers, dependent: :destroy
  has_many :items, dependent: :destroy
  has_many :estimates, dependent: :destroy
  accepts_nested_attributes_for :company, allow_destroy: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, uniqueness:true, length:{ maximum: 255 },
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, length: { minimum: 6 },
            format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i }
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  before_action :authenticate_user!
  before_action :set_company

  def edit
  end

  def update
    binding.pry
    if @company.update(company_params)
      redirect_to user_path(@user)
    else
      redirect_to edit_company_path
    end
  end

  private

  def set_company
    @user = current_user
    @company = @user.company
  end

  def company_params
    params.require(:company).permit(:name, :tel, :fax, :postal_code, :address).merge(user_id: current_user.id)
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  before_action :authenticate_user!


  def index
    @user = current_user
    @customers = @user.customers
  end

  def show
  end

  def new
    @customer = Customer.new
    @customer.contact_persons.build
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      redirect_to customers_path
    else
      @customer = Customer.new(customer_new)
      render :new
    end
  end

  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to customers_path
    else
      render :edit
    end
  end

  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy
    redirect_to customers_path, alert: '削除しました'
  end

  private

  def customer_params
    params.require(:customer).permit(
      :company_name,
      contact_persons_attributes: [:id, :customer_id, :department, :position, :name]
    ).merge(user_id: current_user.id)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @user = current_user
  end

  def show
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :authenticate_user!

  def index
    @user = current_user
    @items = @user.items
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to items_path, notice: '商品を登録しました。'
    else
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to items_path
    else
      render :edit
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_path, alert: '商品を削除しました'
  end

  private

  def item_params
    params.require(:item).permit(
      :item_name
    ).merge(user_id: current_user.id)
  end
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController

  before_action :save_step1_to_session, only: :step2
  before_action :save_step2_to_session, only: :step3

  def step1
    @user = User.new
    @user.build_company
  end

  def save_step1_to_session
    session[:user_params] = user_params
    @user = User.new(session[:user_params])
    render '/signup/step1' unless @user.valid?
  end 

  def step2
    session[:user_params] = user_params
    @user = User.new
    @user.build_company
  end

  def create
    @user = User.new(session[:user_params])
    @user.build_company(user_params[:company_attributes])
    if @user.save
      session[:id] = @user.id
      sign_in @user
      redirect_to root_path
    else
      @user.build_company(user_params[:company_attributes])
      render '/signup/step2'
    end
  end

  private
  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :password, 
      :password_confirmation, 
      company_attributes: [:id, :name, :tel, :fax, :postal_code, :address]
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def index
  end
  
  def show
    @user = User.find(params[:id])
    @company = @user.company
    @estimates = @user.estimates.order("created_at DESC")
  end

  def edit
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/estimate_details_helper.rb
module EstimateDetailsHelper
end

app/helpers/estimates_helper.rb
module EstimatesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/companies/edit.html.haml
.main
  .form
    %h1.form__title
      会社情報編集
    .form__content
      .form__content__input
        = form_for @company, url: company_path(@company) do |f|
          = render 'layouts/error_messages', model: f.object
          .input-area
            = f.label :name, "会社名", class: "input-area__title"
            %span.input-area__required 必須
            %br/
            = f.text_field :name, autofocus: true, autocomplete: "name", class: "input-area__text-field"
          .input-area
            = f.label :tel, "電話番号", class: "input-area__title"
            %span.input-area__required 必須
            %br/
            = f.text_field :tel, autofocus: true, autocomplete: "tel", class: "input-area__text-field"
          .input-area
            = f.label :fax, "FAX番号", class: "input-area__title"
            %span.input-area__required 必須
            %br/
            = f.text_field :fax, autofocus: true, autocomplete: "fax", class: "input-area__text-field"
          .input-area
            = f.label :postal_code, "郵便番号", class: "input-area__title"
            %span.input-area__required 必須
            %br/
            = f.text_field :postal_code, autofocus: true, autocomplete: "postal_code", class: "input-area__text-field"
          .input-area
            = f.label :address, "住所", class: "input-area__title"
            %span.input-area__required 必須
            %br/
            = f.text_field :address, autofocus: true, autocomplete: "address", class: "input-area__text-field"
          .input-area
            = f.submit "更新", class: "submit-btn"

app/views/companies/index.html.haml
%h1 Companies#index
%p Find me in app/views/companies/index.html.erb

app/views/companies/show.html.haml
%h1 Companies#show
%p Find me in app/views/companies/show.html.erb

app/views/customers/edit.html.haml
.main
  .form
    %h1.form__title
      顧客情報編集
    .form__content
      .form__content__input
        = form_with model: @customer, local: true do |f|
          .input-area
            = f.label :company_name, "顧客会社名", class: "input-area__title"
            %span.input-area__required 必須
            %br/
            = f.text_field :company_name, autofocus: true, autocomplete: "company_name", class: "input-area__text-field"
          .input-area
            = f.submit "登録", class: "submit-btn"

app/views/customers/index.html.haml
.main
  .customer-index
    .customer-index__header
      %h1.customer-index__header__title
        取引先一覧
      %div
        = link_to "顧客登録", new_customer_path, class: "new_customer_btn"
    .customer-index__contents
      - if @customers.present?
        - @customers.each do |customer|
          .customer-index__contents__info
            .customer-index__contents__info__company
              = customer.company_name
            .customer-index__contents__info__nav
              .customer-index__contents__info__nav__btn
                = link_to "編集", edit_customer_path(customer)
              .customer-index__contents__info__nav__btn
                = link_to "削除", customer_path(customer), method: :delete
      - else
        %p 顧客の登録はありません。

app/views/customers/new.html.haml
.main
  .form
    %h1.form__title
      顧客登録ページ
    .form__content
      .form__content__input
        = form_with model: @customer, local: true do |f|
          .input-area
            = f.label :company_name, "顧客会社名", class: "input-area__title"
            %span.input-area__required 必須
            %br/
            = f.text_field :company_name, autofocus: true, autocomplete: "company_name", class: "input-area__text-field"
          = f.fields_for :contact_persons do |cp|
            .input-area
              = cp.label :department, "部署名", class: "input-area__title"
              = cp.text_field :department, autofocus: true, autocomplete: "department", class: "input-area__text-field"
            .input-area
              = cp.label :position, "役職", class: "input-area__title"
              = cp.text_field :position, autofocus: true, autocomplete: "position", class: "input-area__text-field"
            .input-area
              = cp.label :name, "担当者名", class: "input-area__title"
              %span.input-area__required 必須
              %br/
              = cp.text_field :name, autofocus: true, autocomplete: "name", class: "input-area__text-field"
          .input-area
            = f.submit "登録", class: "submit-btn"

app/views/items/destroy.html.haml
%h1 Items#destroy
%p Find me in app/views/items/destroy.html.erb

app/views/items/edit.html.haml
.main
  .form
    %h1.form__title
      商品情報編集
    .form__content
      .form__content__input
        = form_with model: @item, local: true do |f|
          .input-area
            = f.label :item_name, "商品名", class: "input-area__title"
            %span.input-area__required 必須
            %br/
            = f.text_field :item_name, autofocus: true, autocomplete: "item_name", class: "input-area__text-field"
          .input-area
            = f.submit "登録", class: "submit-btn"

app/views/items/index.html.haml
.main
  .item-index
    .item-index__header
      %h1.item-index__header__title
        商品一覧
      %div
        = link_to "商品登録", new_item_path, class: "new_item_btn"
    .item-index__contents
      - if @items.present?
        - @items.each do |item|
          .item-index__contents__info
            .item-index__contents__info__company
              = item.item_name
            .item-index__contents__info__nav
              .item-index__contents__info__nav__btn
                = link_to "編集", edit_item_path(item)
              .item-index__contents__info__nav__btn
                = link_to "削除", item_path(item), method: :delete
      - else
        %p 登録商品はありません。

app/views/items/new.html.haml
.main
  .form
    %h1.form__title
      商品登録ページ
    .form__content
      .form__content__input
        = form_with model: @item, local: true do |f|
          .input-area
            = f.label :item_name, "商品名", class: "input-area__title"
            %span.input-area__required 必須
            %br/
            = f.text_field :item_name, autofocus: true, autocomplete: "item_name", class: "input-area__text-field"
          .input-area
            = f.submit "登録", class: "submit-btn"

app/views/items/update.html.haml
%h1 Items#update
%p Find me in app/views/items/update.html.erb

app/views/users/index.html.haml
.main
  .main__indexpage
    .main__indexpage__content
      .main__indexpage__content__headerwrapper
        .main__indexpage__content__headerwrapper__title
          最近の見積書
        .main__indexpage__content__headerwrapper__nav
          すべて見る

app/views/users/show.html.haml
.main
  .mypage
    %h1.mypage__title
      = @user.name
      様の登録情報
    .mypage__content
      .profile
        .profile__header
          %h3 会員登録情報
        .profile__body
          %table.informationbox
            %tr.informationbox__inner
              %th.user-info 基本情報
              %td.details
                %p.details__big= @user.name
                %p= @user.email
                %br/
              %td.change
                %p.btn
                  = link_to "ユーザー編集", edit_user_registration_path, class: "edit-btn"
            %tr.informationbox__inner
              %th.company-info 会社情報
              %td.details
                %p.details__middle= @company.name
                %p
                  〒#{@company.postal_code}
                %p= @company.address
                %p
                  電話番号:#{@company.tel}
                %p
                  FAX番号:#{@company.fax}
              %td.change
                %p.btn
                  = link_to "会社情報編集", edit_company_path, class: "edit-btn"

  .estimates
    %h1.estimates__title
      見積履歴
      = link_to "一覧", estimates_path(@user)
    .estimates__content
      .estimate
        .estimate__header
          %h3 
        .estimate__body
          .informationbox
            - @estimates.last(5).each do |estimate|
              .informationbox__inner
                = l estimate.created_at, format: :short
                .estimate-content
                  .customer-info
                    .customer-info__company
                      #{estimate.customer.company_name} 御中
                    .customer-info__department
                      = estimate.contact_person.department
                    .customer-info__position
                      = estimate.contact_person.position
                    .customer-info__name
                      #{estimate.contact_person.name} 様
                  .details
                    - estimate.estimate_details.each.with_index do |detail, index|
                      .details__info
                        .details__info__item-name
                          #{index + 1} #{detail.item.item_name}
                        .details__info__volume
                          #{detail.volume} 個
                        .details__info__price
                          #{detail.price} 円